Wip/DEV_Source/SMDH/SMDH/Areas/Customer/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMDH.Models;
using SMDH.Models.Concrete;
using SMDH.Models.Statuses;
using System.Web.Security;

namespace SMDH.Areas.Customer.Controllers
{
    public partial class DashboardController : CustomerDefaultController
    {
        SMDHDataContext context = new SMDHDataContext();

        public virtual ActionResult Index()
        {
            var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            var requests = context.Requests.Where(r => r.CustomerId == userInfo.CustomerId).ToList();
            var orders = context.Orders.Where(o => o.Request.CustomerId == userInfo.CustomerId).ToList();
            ViewBag.CustomerId = userInfo.CustomerId;
            //var requests = context.Requests.Where(r => r.CustomerId == 1).ToList();
            //var orders = context.Orders.Where(o => o.Request.CustomerId == 1).ToList();

            var numberOfRequestsList = new List<int>();
            numberOfRequestsList.Add(requests.Where(r => r.RequestStatus == (int)RequestStatus.New).Count());
            numberOfRequestsList.Add(requests.Where(r => r.RequestStatus == (int)RequestStatus.Pricing).Count());
            numberOfRequestsList.Add(requests.Where(r => r.RequestStatus == (int)RequestStatus.Approved).Count());
            numberOfRequestsList.Add(requests.Where(r => r.RequestStatus == (int)RequestStatus.Collected).Count());
            numberOfRequestsList.Add(requests.Where(r => r.RequestStatus == (int)RequestStatus.Canceled).Count());

            ViewBag.NumberOfRequests = numberOfRequestsList;

            var numberOfOrdersList = new List<int>();
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.Draft).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.RePricingApproveRequest).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.ReturnedReducePrice || 
                o.OrderStatus == (int)OrderStatus.Expired).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.PlannedForCollecting).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.Delivering).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.ToBeReturned).Count());
            numberOfOrdersList.Add(orders.Where(o => o.OrderStatus == (int)OrderStatus.ConfirmReturned).Count());
            ViewBag.NumberOfOrders = numberOfOrdersList;

            return View();
        }
    }
}

Wip/DEV_Source/SMDH/SMDH/Areas/Customer/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SMDH.Models;
using SMDH.Models.Statuses;
using SMDH.Models.Concrete;
using SMDH.Models.ViewModels;
using System.Net;
using SMDH.Helpers;
using Newtonsoft.Json;
using System.IO;

namespace SMDH.Areas.Customer.Controllers
{
    public class OrdersController : CustomerDefaultController
    {
        private SMDHDataContext context = new SMDHDataContext();

        public ViewResult Index()
        {
            var orders = new List<Order>();
            var statuses = new List<int>();
            statuses.Add((int)OrderStatus.New);
            statuses.Add((int)OrderStatus.Approved);
            statuses.Add((int)OrderStatus.PlannedForCollecting);
            statuses.Add((int)OrderStatus.Collected);
            statuses.Add((int)OrderStatus.ToBeReturned);
            statuses.Add((int)OrderStatus.PlannedForDelivering);

            try
            {
                if (!string.IsNullOrEmpty(Request["status"]))
                {
                    var statusStrs = Request["status"].Split(',');
                    if (statusStrs.Count() > 0)
                    {
                        statuses = new List<int>();
                        foreach (var statusStr in statusStrs)
                        {
                            switch (statusStr.ToLower())
                            {
                                case "draft": statuses.Add((int)OrderStatus.Draft);
                                    break;
                                case "new": statuses.Add((int)OrderStatus.New);
                                    break;
                                case "approved": statuses.Add((int)OrderStatus.Approved);
                                    break;
                                case "plannedforcollecting": statuses.Add((int)OrderStatus.PlannedForCollecting);
                                    break;
                                case "delivering": statuses.Add((int)OrderStatus.Delivering);
                                    break;
                                case "collected": statuses.Add((int)OrderStatus.Collected);
                                    break;
                                case "tobereturned": statuses.Add((int)OrderStatus.ToBeReturned);
                                    break;
                                case "plannedfordelivering": statuses.Add((int)OrderStatus.PlannedForDelivering);
                                    break;
                                case "delivered": statuses.Add((int)OrderStatus.Delivered);
                                    break;
                                case "returned": statuses.Add((int)OrderStatus.Returned);
                                    break;
                                case "canceled": statuses.Add((int)OrderStatus.Canceled);
                                    break;
                                case "rejected": statuses.Add((int)OrderStatus.Rejected);
                                    break;
                                case "returnedreduceprice": statuses.Add((int)OrderStatus.ReturnedReducePrice);
                                    break;
                                case "expired": statuses.Add((int)OrderStatus.Expired);
                                    break;
                                case "repricingapproverequest": statuses.Add((int)OrderStatus.RePricingApproveRequest);
                                    break;
                                case "confirmreturned": statuses.Add((int)OrderStatus.ConfirmReturned);
                                    break;
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
            }

            if (statuses.Count == 1 && statuses.ElementAt(0) == (int)OrderStatus.Draft)
            {
                ViewBag.ApproveAllDisplay = true;
            }
            else
            {
                ViewBag.ApproveAllDisplay = false;
            }
            var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            orders = context.Orders.Where(o => o.CustomerId == userInfo.CustomerId
                                            && statuses.Contains(o.OrderStatus)).ToList();
            //orders = context.Orders.Where(o => o.Request.CustomerId == 1//userInfo.CustomerId
            //                                && statuses.Contains(o.OrderStatus)).ToList();
            ViewBag.Customer = userInfo.Customer.CompanyName;

            if (!string.IsNullOrWhiteSpace(Request["startDate"]))
            {
                var startDate = DateTime.ParseExact(Request["startDate"].Trim(), "ddMMyyyy", null);
                orders = orders.Where(o => o.CreatedDate >= startDate).ToList();
                ViewBag.StartDate = string.Format("{0:dd/MM/yyyy}", startDate);
            }
            if (!string.IsNullOrWhiteSpace(Request["endDate"]))
            {
                var endDate = DateTime.ParseExact(Request["endDate"].Trim(), "ddMMyyyy", null);
                orders = orders.Where(o => o.CreatedDate <= endDate).ToList();
                ViewBag.EndDate = string.Format("{0:dd/MM/yyyy}", endDate);
            }

            ViewBag.SelectedStatuses = statuses;

            return View(orders);
        }

        //
        // GET: /CustomerSideOrder/Details/5

        public ViewResult Details(int id)
        {
            var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            //var order = context.Orders.Find(id);
            var order = context.Orders.Single(o => o.OrderId == id);
            if (order.CustomerId != userInfo.CustomerId) throw new HttpException(404, "Not found!");
            ViewBag.Customer = userInfo.Customer.CompanyName;
            ViewBag.Items = context.Items.Where(i => i.OrderId == id).ToList();

            return View(order);
        }

        //
        // GET: /CustomerSideOrder/Create

        public ActionResult Create(int requestId)
        {
            var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            //var request = context.Requests.Find(requestId);
            var request = context.Requests.Single(o => o.RequestId == requestId);
            if (request.CustomerId != userInfo.CustomerId) throw new HttpException(404, "Not found!");
            ViewBag.Customer = "Test Company";//userInfo.Customer.CompanyName;
            ViewBag.PossibleCityProvinces = new SelectList(context.CityProvinces.Where(cp => cp.IsActive).ToArray(), "CityProvinceId", "Name");
            ViewBag.PossibleDistricts = new SelectList(new List<District>());
            ViewBag.PossibleWards = new SelectList(new List<Ward>());
            ViewBag.PossibleDeliveryOptions = new SelectList(context.DeliveryOptions.Where(d => d.IsActive).ToList(), "DeliveryOptionId", "Name");
            ViewBag.PossiblePaymentTypes = new SelectList(context.OrderPaymentTypes.Where(op => op.IsActive).ToList(), "OrderPaymentTypeId", "Name");
            ViewBag.RequestId = requestId;
            return View();
        }

        //
        // POST: /CustomerSideOrder/Create

        [HttpPost]
        public ActionResult ConfirmCreate(Order order)
        {
            try
            {
                var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
                var request = context.Requests.Single(r => r.RequestId == order.RequestId);
                order.OrderStatus = (int)OrderStatus.New;
                order.CreatedDate = DateTime.Now;
                order.CustomerId = userInfo.CustomerId;
                GetLatitudeAndLongitudeFromAddress(order);
                EFOrdersRepository orderRepo = new EFOrdersRepository();
                if (request.CustomerId != userInfo.CustomerId) return Json(new { success = false });
                ViewBag.Customer = userInfo.Customer.CompanyName;

                if (orderRepo.AddToRequest(request, order))
                {
                    var myContext = new SMDHDataContext();
                    order = myContext.Orders.Single(o => o.OrderId == order.OrderId);
                    var orderDetails = new OrderViewModel(order);
                    return Json(new { success = true, order = orderDetails });
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return Json(new { success = false });
            }
        }

        //
        // GET: /CustomerSideOrder/Edit/5

        [HttpPost]
        public ActionResult Edit(int id)
        {
            var userInfo = context.UserInfos.Single(uf => uf.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            var order = context.Orders.Single(o => o.OrderId == id);
            if (order.Request.CustomerId != userInfo.CustomerId) throw new HttpException(404, "Not found!");
            ViewBag.Customer = userInfo.Customer.CompanyName;
            ViewBag.PossibleCityProvinces = new SelectList(context.CityProvinces.Where(cp => cp.IsActive).ToArray(), "CityProvinceId", "Name", order.District.CityProvinceId);
            ViewBag.PossibleDistricts = new SelectList(order.District.CityProvince.Districts.Where(d => d.IsActive), "DistrictId", "Name", order.ReceiverAddressDistrictId);

Wip/DEV_Source/SMDH/SMDH/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMDH.Models.Concrete;
using SMDH.Models;
using System.Web.Security;

namespace SMDH.Controllers
{
    [Authorize(Roles="Office Staff")]
    public class DashboardController : Controller
    {
        SMDHDataContext context = new SMDHDataContext();
        //
        // GET: /Dashboard/
        public ActionResult Index()
        {
            ViewBag.UserInfo = context.UserInfos.Single(r => r.UserId == (Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
             return View();
        }

    }
}

Wip/DEV_Source/SMDH/SMDH/Areas/Hub/Views/Dashboard/OrderTable.cshtml
@model IEnumerable<SMDH.Models.Order>
@using System.Text.RegularExpressions;
@using SMDH.Models.Statuses;
@{
    Layout = null;
}

@using (Html.BeginForm("ChangeStatus", "Dashboard"))
{
    int count = 1;
    <table class="table table-striped table-bordered" id="main-table">
        <thead>
            <tr>
                <th></th>
                <th>No.
                </th>
                <th>OrderID
                </th>
                <th>Item No.
                </th>
                <th>Price
                </th>
                <th>Delivery Date
                </th>
                <th>Expired Date
                </th>
                <th>Status
                </th>

                <th class="tbl-action-col">Action
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <td>@if (@Model.ElementAt(@i).Status.ToString() == @OrderStatus.DeliveringToHub.ToString()) //|| @Model.ElementAt(0).Status.ToString() == OrderStatus.WaitingForReturn.ToString())
                        {
                        <input type="checkbox" id="@Model.ElementAt(i).OrderId" value="@Model.ElementAt(i).OrderId" name="selectedObjects"/>
                        }</td>
                    <td>
                        @(count + i)
                    </td>
                    <td>
                        @Model.ElementAt(@i).OrderId
                    </td>
                    <td>
                        @Model.ElementAt(@i).Items.Count
                    </td>
                    <td>
                        @if (@Model.ElementAt(@i).Fee != null)
                        {
                            @Model.ElementAt(@i).Fee
                        }
                        else
                        {
                            <span class="label label-important">Not set yet</span><text>&nbsp;</text>
                        }
                    </td>
                    <td>
                        @if (@Model.ElementAt(@i).DeliveryDate != null)
                        {
                            @string.Format("{0:dd/MM/yyyy hh:mm tt}", @Model.ElementAt(@i).DeliveryDate)
                        }
                        else
                        {
                            <span class="label label-important">Not set yet</span><text>&nbsp;</text>
                        }
                    </td>
                    <td>
                        @if (@Model.ElementAt(@i).DeliveryDate != null)
                        {
                        
                            @string.Format("{0:dd/MM/yyyy hh:mm tt}", @Model.ElementAt(@i).DeliveryDate.Value.AddDays(3))
                        
                        }
                        else
                        {
                            <span class="label label-important">Not set yet</span><text>&nbsp;</text>
                        }
                    </td>
                    <td>
                        @Model.ElementAt(@i).Status
                    </td>
                    <td class=" action-column">
                        <a class="btn action view" href="Orders/Details/@Model.ElementAt(@i).OrderId">
                            <img src="/img/icons/notepad.png" alt="Detail" title="View" width="12px"></a>
                        @if (@Model.ElementAt(@i).Status.ToString() == @OrderStatus.Delivering.ToString())
                        {
                            <a class="btn action view" href="Orders/Edit/@Model.ElementAt(@i).OrderId">
                                <img src="/img/icons/notepencil32.png" alt="Edit" title="Update" width="12px"></a>
                            
                            <a class="btn btn-primary" href="">ChangeStatus</a>
                        }
                    </td>
                </tr>
            }
            <br />

        </tbody>
    </table>
@*            if (@Model.ElementAt(0).Status.ToString() == OrderStatus.DeliveringToHub.ToString() || @Model.ElementAt(0).Status.ToString() == OrderStatus.WaitingForReturn.ToString())
            {
    <input value="Change Status" type="submit" style="float: left" />
            }*@

}



@*@foreach (var item in Model)
        {
            <tr>
                <td>#@item.OrderId
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy hh:mm tt}", item.Request.RequestedDate)
                </td>
                <td>
                    @item.FullAddress
                </td>
                <td>
                    @item.AmountToBeCollectedFromReceiver
                </td>
                <td>
                    @(item.DeliveryOption == null ? "None" : item.DeliveryOption.Name)
                </td>
                <td>
                    @(item.OrderPaymentType == null ? "None" : item.OrderPaymentType.Name)
                </td>
                <td>
                    @Regex.Replace(item.Status.ToString(), "(\\B[A-Z])", " $1")
                </td>
                <td>
                    @if (item.DueDate != null)
                    {
                        @String.Format("{0:dd/MM/yyyy hh:mm tt}", item.DueDate)
                    }
                    else
                    {
                        <span class="label label-important">Not set yet</span><text>&nbsp;</text>
                    }
                </td>
                <td>
                    @if (item.DueDate != null)
                    {
                        @String.Format("{0:yyyyMMddHHmm}", item.DueDate)
                    }
                    else
                    {
                        <text>000</text>
                    }
                </td>
                <td>
                    @if (item.Fee != null)
                    {
                        @item.Fee
                    }
                    else
                    {
                        <span class="label label-important">Not set yet</span><text>&nbsp;</text>
                    }
                </td>
                <td>
                    @if (!string.IsNullOrWhiteSpace(item.Note))
                    {
                        @item.Note
                    }
                    else
                    {
                        <text>None</text>
                    }
                </td>
                <td class=" action-column">
                    <a class="btn action view" href="Orders/Details/@item.OrderId">
                        <img src="/img/icons/notepad.png" alt="View" title="View" width="12px"></a>
                    @if (item.Status == HDMS.Models.Statuses.OrderStatus.Draft || item.Status == HDMS.Models.Statuses.OrderStatus.Rejected)
                    {
                        <a class="btn action delete" href="#" onclick="cancelOrder(@item.OrderId);">
                            <img src="/img/icons2/cross.png" alt="Cancel" title="Cancel" width="12px" />
                        </a>        
                    }
                </td>
            </tr>
        }*@


Wip/DEV_Source/SMDH/SMDH/Areas/Hub/Views/Dashboard/ViewInformationOrder.cshtml
@{
    ViewBag.Title = "ViewInformationOrder";
}

<link rel="stylesheet" type="text/css" href="/css/select2.css" />
<script type="text/javascript" charset="utf-8" language="javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8" language="javascript" src="/js/DT_bootstrap.js"></script>
<script src="/js/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@*<script src="/js/crud.js" type="text/javascript"></script>*@
<script src="/js/form-action.js" type="text/javascript"></script>
<script src="/js/chosen.jquery.js" type="text/javascript"></script>
<link href="/css/datepicker.css" rel="stylesheet" type="text/css" />
<script src="/js/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="/js/date.js" type="text/javascript"></script>
<script src="/js/accounting.js" type="text/javascript"></script>
<script>
    function showTable() {
        document.getElementById('table').style.visibility = "visible";
    }
    function hideTable() {
        document.getElementById('table').style.visibility = "hidden";
    }
</script>
<script>
    var asInitVals = new Array();
    $(function () {
        var oTable = $('#example').dataTable({
            "oLanguage": {
                "sSearch": "Search :"
            }
        });

        $("tfoot input").keyup(function () {
            /* Filter on the column (the index) of this element */
            oTable.fnFilter(this.value, $("tfoot input").index(this));
        });



        /*
        * Support functions to provide a little bit of 'user friendlyness' to the textboxes in
        * the footer
        */
        $("tfoot input").each(function (i) {
            asInitVals[i] = this.value;
        });

        $("tfoot input").focus(function () {
            if (this.className == "search_init") {
                this.className = "";
                this.value = "";
            }
        });

        $("tfoot input").blur(function (i) {
            if (this.value == "") {
                this.className = "search_init";
                this.value = asInitVals[$("tfoot input").index(this)];
            }
        });
    });
</script>
<body data-spy="scroll" data-target=".bs-docs-sidebar" id="dt_example" onload="javascript:hideTable()">
    <h2>Please enter your phone number to view order</h2>
    <div class="widget">
        <div class="widget-header">
            <div class="title">
                Tracking Order
            </div>
        </div>
        <div class="widget-body">
            <form action="javascript:void(0);" class="form-horizontal">
                <div class="control-group">
                    <label class="control-label">
                        Phone Number :</label>
                    <div class="controls">
                        @if (ViewBag.PhoneNumber.Length != 0)
                        {
                            <input type="text" id="txtPhoneNumber" value="@ViewBag.PhoneNumber"/>
                        }
                        else
                        {
                            <input type="text" id="txtPhoneNumber" />
                        }
                        <button type="submit" class="btn btn-primary" id="btnOk">
                            Confirm</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">

            <div id="demo">
                <table cellpadding="0" cellspacing="0" border="0" class="table" id="table">
                    <thead>
                        <tr>
                            <th>Order No
                            </th>
                            <th>Order Date
                            </th>
                            <th>Status
                            </th>
                            <th>Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="success">
                            <td>1
                            </td>
                            <td>20/03/2013
                            </td>
                            <td>New
                            </td>

                            <td>
                                <a href="#myModal" role="button" class="btn btn-mini btn-success" data-toggle="modal" style="color: white;">View Detail</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-header">
            <h3 id="myModalLabel">Passcode</h3>
        </div>
        <div class="modal-body" style="text-align: center">
            <form class="form-horizontal" action="/Hub/Dashboard/ViewOrderDetails" id="passcodeForm">
                <fieldset>
                    <label>Please enter the passcode to view order detail:</label></br>
            		<input type="text" id="txtPasscode" name="txtPasscode" />
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" id="btnSubmit">
                Ok</button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">
                Cancel</button>
        </div>
    </div>
    <script type="text/javascript">
        $().ready(function () {
            if ($('#txtPhoneNumber').val() != "") {
                loadOrdersTable();
            }
        });
        $('#btnSubmit').click(function () {
            $('#passcodeForm').submit();
        });

        $('#btnOk').click(function (event) {
            hideTable();
            if ($('#txtPhoneNumber').val() == '') {
                bootbox.alert("Please enter phone number!");
                $('#txtPhoneNumber').focus();
                return;
            } else {
                loadOrdersTable();
            }
        });

        function loadOrdersTable() {
            $.post("/Hub/Dashboard/GetOrdersByPhone", { phoneNumber: $('#txtPhoneNumber').val() }, function (result) {
                if (result.length == 0) {
                    bootbox.alert("0 records found");
                } else {
                    var strTable = '<table cellpadding="0" cellspacing="0" border="0" class="table" id="table" width = "800px">' +
                                '<thead>' +
                                    '<tr>' +
                                        '<th>' +
                                            'Order No' +
                                        '</th>' +
                                        '<th>' +
                                            'Order Date' +
                                        '</th>' +
                                        '<th>' +
                                            'Status' +
                                        '</th>' +
                                        '<th>' +
                                            'Action' +
                                        '</th>' +
                                    '</tr>' +
                                '</thead>' +
                                 '<tbody>';
                    for (var i = 0; i < result.length; i++) {
                        strTable += '<tr class="success">' +
                                        '<td>' +
                                            result[i].OrderId +
                            '</td>' +
                                        '<td>' +
                                            result[i].CreatedDate +
                                        '</td>' +
                                        '<td>' +
                                            result[i].Status +
                            '</td>' +
                                        '<td>' +
                                            '<a href="#myModal" role="button" class="btn btn-mini btn-success" data-toggle="modal" style="color:white;">View Detail</a>' +
                                        '</td>' +
                                    '</tr>';
                    }
                    strTable += '</tbody>' +
                            '</table>';
                    $('#demo').html(strTable);
                    showTable();
                }
            });
        }
    </script>
</body>