Wip/DEV_Source/HDMS/HDMS/Models/Request.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Orders = new HashSet<Order>();
            this.Cargoes = new HashSet<Cargo>();
        }
    
        public int RequestId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public int CustomerId { get; set; }
        public int CollectionAddressId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> CollectionPlanId { get; set; }
        public int RequestStatus { get; set; }
        public string Note { get; set; }
    
        public virtual CollectionPlan CollectionPlan { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Cargo> Cargoes { get; set; }
    }
}

Wip/DEV_Source/HDMS/HDMS/Models/ViewModels/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using HDMS.Models;
using HDMS.Models.Utilities;
using HDMS.Models.ViewModels;

public partial class RequestViewModel
{
    public int RequestId { get; set; }
    public string Customer { get; set; }
    public string CollectionAddress { get; set; }
    public string RequestedDate { get; set; }
    public string Status { get; set; }
    public string Note { get; set; }
    public Nullable<decimal> Latitude { get; set; }
    public Nullable<decimal> Longitude { get; set; }
    public string AddressFromWard { get; set; }
    public float WeightedScore { get; set; }

    public RequestViewModel(Request request)
    {
        RequestId = request.RequestId;
        Customer = request.Customer.DisplayName;
        CollectionAddress = request.CustomerAddress.FullAddress;
        RequestedDate = string.Format("{0:dd/MM/yyyy tt}", request.RequestedDate);
        Status = Regex.Replace(request.Status.ToString(), "(\\B[A-Z])", " $1");
        Note = request.Note;
        Latitude = request.CustomerAddress.Latitude;
        Longitude = request.CustomerAddress.Longitude;
        AddressFromWard = AddressHelper.GetAddressFromWard(request.CustomerAddress);
    }

    public RequestViewModel(Request request, float weightedDeliveryTypeScore, float weightedDateScore)
    {
        RequestId = request.RequestId;
        Customer = request.Customer.DisplayName;
        CollectionAddress = request.CustomerAddress.FullAddress;
        RequestedDate = string.Format("{0:dd/MM/yyyy tt}", request.RequestedDate);
        Status = Regex.Replace(request.Status.ToString(), "(\\B[A-Z])", " $1");
        Note = request.Note;
        Latitude = request.CustomerAddress.Latitude;
        Longitude = request.CustomerAddress.Longitude;
        AddressFromWard = AddressHelper.GetAddressFromWard(request.CustomerAddress);
        System.TimeSpan diff = System.DateTime.Now.Subtract(DateTime.Parse(RequestedDate, new System.Globalization.CultureInfo("fr-FR", false)));
        WeightedScore = weightedDateScore * diff.Days + weightedDeliveryTypeScore;
    }
}

Wip/DEV_Source/HDMS/HDMS/Areas/Customer/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HDMS.Models;
using HDMS.Models.Statuses;

namespace HDMS.Areas.Customer.Controllers
{
    public class RequestsController : CustomerDefaultController
    {
        private HDMSEntities context = new HDMSEntities();

        //
        // GET: /CRCustomer/
        public ViewResult Index()
        {
            var requests = new List<Request>();
            var statuses = new List<int>();
            statuses.Add((int)RequestStatus.New);
            statuses.Add((int)RequestStatus.Approved);
            statuses.Add((int)RequestStatus.PlannedForCollecting);
            statuses.Add((int)RequestStatus.Collected);
            try
            {
                if (!string.IsNullOrEmpty(Request["status"]))
                {
                    var statusStrs = Request["status"].Split(',');
                    if (statusStrs.Count() > 0)
                    {
                        statuses = new List<int>();
                        foreach (var statusStr in statusStrs)
                        {
                            switch (statusStr.ToLower())
                            {
                                case "draft": statuses.Add((int)RequestStatus.Draft);
                                    break;
                                case "new": statuses.Add((int)RequestStatus.New);
                                    break;
                                case "approved": statuses.Add((int)RequestStatus.Approved);
                                    break;
                                case "planned": statuses.Add((int)RequestStatus.PlannedForCollecting);
                                    break;
                                case "collected": statuses.Add((int)RequestStatus.Collected);
                                    break;
                                case "finished": statuses.Add((int)RequestStatus.Finished);
                                    break;
                                case "canceled": statuses.Add((int)RequestStatus.Canceled);
                                    break;
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
            }
            
            var userInfo = context.UserInfoes.Find((Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            requests = userInfo.Customer.Requests.Where(r => statuses.Contains(r.RequestStatus)).ToList();
            ViewBag.Customer = userInfo.Customer.CompanyName;

            if (!string.IsNullOrWhiteSpace(Request["startDate"]))
            {
                var startDate = DateTime.ParseExact(Request["startDate"], "ddMMyyyy", null);
                requests = requests.Where(r => r.RequestedDate >= startDate).ToList();
                ViewBag.StartDate = string.Format("{0:dd/MM/yyyy}", startDate);
            }
            if (!string.IsNullOrWhiteSpace(Request["endDate"]))
            {
                var endDate = DateTime.ParseExact(Request["endDate"], "ddMMyyyy", null).AddDays(1);
                requests = requests.Where(r => r.RequestedDate <= endDate).ToList();
                ViewBag.EndDate = string.Format("{0:dd/MM/yyyy}", DateTime.ParseExact(Request["endDate"], "ddMMyyyy", null));
            }

            ViewBag.SelectedStatuses = statuses;
            return View(requests);
        }

        //public ActionResult Index()
        //{
        //    var currentUser = Membership.GetUser(User.Identity.Name);
        //    var userInfo = context.UserInfoes.Find((Guid) currentUser.ProviderUserKey);
        //    var requests = userInfo.Customer.Requests.ToList();

        //    return View(requests);
        //}

        //
        // GET: /Requests/Details/5

        public ViewResult Details(int id)
        {
            var userInfo = context.UserInfoes.Find((Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            Request request = context.Requests.Find(id);
            if(request.CustomerId == userInfo.CustomerId)
            {
                if (request != null)
                {
                    ViewBag.Customer = userInfo.Customer.CompanyName;
                    return View(request);
                }   
            }
            throw new HttpException(404, "Not found!");
        }

        //private class JsonRequest
        //{
        //    public int RequestId { get; set; }
        //    public string CustomerDisplayName { get; set; }
        //    public string CollectionAddress { get; set; }
        //    public Nullable<System.DateTime> RequestedDate { get; set; }
        //}

        //[HttpPost]
        //public ActionResult GetRequestsOfCityProvince(int id)
        //{
        //    var requests = context.Requests.Where(cr => cr.CustomerAddress.District.CityProvinceId == id)
        //        .Include(cr => cr.Customer).Include(cr => cr.CustomerAddress);
        //    if (requests != null)
        //    {
        //        var jsonRequests = new List<JsonRequest>();
        //        foreach (var request in requests)
        //        {
        //            var jsonRequest = new JsonRequest
        //            {
        //                RequestId = request.RequestId,
        //                RequestedDate = request.RequestedDate,
        //                CustomerDisplayName = request.Customer.DisplayName,
        //                CollectionAddress = request.CollectionAddress
        //            };
        //            jsonRequests.Add(jsonRequest);
        //        }
        //        return Json(new { success = true, jsonRequests });
        //    }
        //    return Json(new { success = false });
        //}

        [HttpPost]
        public ActionResult Create()
        {
            var userInfo = context.UserInfoes.Find((Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
            ViewBag.PossibleCollectionAddresses = userInfo.Customer.CustomerAddresses.Where(ca => ca.IsActive);
            return View();
        }

        [HttpPost]
        public ActionResult ConfirmCreate(int collectionAddressId, string note, HttpPostedFileBase excelFile)
        {
            try
            {
                var userInfo = context.UserInfoes.Find((Guid)(Membership.GetUser(User.Identity.Name)).ProviderUserKey);
                var collectionAddress = context.CustomerAddresses.Find(collectionAddressId);
                if (userInfo.CustomerId != collectionAddress.CustomerId) return View("CreateUnsuccessful");
                var request = new Request
                {
                    CustomerId = (int)userInfo.CustomerId,
                    CollectionAddressId = collectionAddressId,
                    Note = note
                };
                if (request.Create(context))
                {
                    if (excelFile != null)
                    {
                        string savedFileName = "~/Excel/" + excelFile.FileName;
                        excelFile.SaveAs(Server.MapPath(savedFileName));

                        var connectionString = string.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=Excel 12.0;", Server.MapPath(savedFileName));
                        OleDbConnection objConn = new OleDbConnection(connectionString);
                        objConn.Open();
                        var dt = objConn.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

                        String[] excelSheets = new String[dt.Rows.Count];
                        int x = 0;

                        foreach (DataRow row in dt.Rows)
                        {
                            excelSheets[x] = row["TABLE_NAME"].ToString();
                            x++;
                        }

                        for (int j = 0; j < excelSheets.Length; j++)
                        {
                            if (excelSheets[j].Contains("Order"))
                            {
                                var adapter = new OleDbDataAdapter("SELECT * FROM " + "[" + excelSheets[j] + "]", connectionString);
                                var ds = new DataSet();
                                adapter.Fill(ds, "results");
                                DataTable data = new DataTable();
                                data = ds.Tables["results"];

                                var orders = new List<Order>();
                                var items = new List<Item>();

                                Order order = new Order();

                                for (int i = 0; i < data.Rows.Count; i++)
                                {
                                    var receiverName = data.Rows[i].Field<string>("Receiver Name");
                                    var receiverPhone = data.Rows[i].Field<string>("Receiver Phone");
                                    var receiverAddress = data.Rows[i].Field<string>("Receiver Address");
                                    var drOption = data.Rows[i].Field<string>("Delivery Option");
                                    var orPaymentType = data.Rows[i].Field<string>("Order Payment Type");
                                    var cityName = data.Rows[i].Field<string>("City");
                                    var districtName = data.Rows[i].Field<string>("District");
                                    var wardName = data.Rows[i].Field<string>("Ward");
                                    var amount = data.Rows[i].Field<string>("Amount");

                                    if (i == 0)
                                    {

Wip/DEV_Source/HDMS/HDMS/Areas/Customer/Views/Requests/Create.cshtml
@model HDMS.Models.Request
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        ×</button>
    <h3 id="myModalLabel">
        Create new Request</h3>
</div>
<div class="modal-body" style="height: 400px;">
    @using (Html.BeginForm("ConfirmCreate", "Requests", FormMethod.Post, new { id = "create-form", Enctype = "multipart/form-data", Class = "form-horizontal" }))
    {
        @Html.ValidationSummary(true)
        <div class="control-group">
            <label class="control-label">
                Collection Address <span style="color:Red">*</span>
            </label>
            <div class="controls">
                @*@Html.DropDownListFor(model => model.CollectionAddressId, ViewBag.PossibleCollectionAddresses as SelectList, "-- Choose a Collection Address --", new { id = "ddlCollectionAddress", Class = "chzn-select" })*@
                @Html.DropDownListFor(model => model.CollectionAddressId, ((IEnumerable<HDMS.Models.CustomerAddress>)ViewBag.PossibleCollectionAddresses).Select(option => new SelectListItem
       {
           Text = Html.DisplayTextFor(_ => option.FullAddress).ToString(),
           Value = option.CustomerAddressId.ToString()
       }), new { id = "ddlCollectionAddress", Class = "chzn-select" })
                @Html.ValidationMessageFor(model => model.CollectionAddressId)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Note
            </label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Note)
                @Html.ValidationMessageFor(model => model.Note)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Excel file
            </label>
            <div class="controls">
                <input type="file" id="excelFile" name="excelFile" />  
            </div>
        </div>
        
    }
</div>
<div class="modal-footer">
    <input id="btnCreate" type="submit" class="btn btn-primary" value="Create" />
    <button class="btn" data-dismiss="modal" aria-hidden="true">
        Cancel</button>
</div>
<script>
    //    $("#create-form").submit(function () {
    //        if ($(this).valid()) {
    //            $.ajax({
    //                type: 'POST',
    //                url: $(this).attr("action"),
    //                data: $(this).serialize(),
    //                success: function (result) {
    //                    if (result.success) {
    //                        window.location = '/Request/AddOrders/' + result.requestId;
    //                    }
    //                },
    //                async: false
    //            });
    //        }
    //        return false;
    //    });

    $('#btnCreate').click(function () {
        $('#create-form').submit();
    });

    $("#ddlCustomer").change(function () {
        var id = $('#ddlCustomer option:selected').val();
        if (id == '') id = -1;
        $.ajax({
            type: 'POST',
            url: '/CustomerAddresses/GetAddressesOfCustomer/' + id,
            success: function (data) {
                var items = '';
                $.each(data, function (i, address) {
                    items += "<option value='" + address.CustomerAddressId + "'>" + address.FullAddress + "</option>";
                });
                $('#ddlCollectionAddress').html(items);
                $('#ddlCollectionAddress').removeAttr('data-val-number');
                $("form").removeData("validator");
                $("form").removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse("form");
                $('#ddlCollectionAddress').trigger("liszt:updated");
            },
            async: false
        });
    });
    $(".chzn-select").chosen();
    $(".chzn-select-deselect").chosen({ allow_single_deselect: true });

    $(".datepicker").datepicker();
</script>
<script>
    $('#uploadExcelForm').submit(function () {
        if (document.getElementById('excelFile').value.match(/xls$/) || document.getElementById('excelFile').value.match(/xlsx$/)) {
            return true;
        } else {
            alert('Must be a excel file !!!!!');
            return false;
        }
    });
</script>

Wip/DEV_Source/HDMS/HDMS/Areas/Customer/Views/Requests/RequestTable.cshtml
@model IEnumerable<HDMS.Models.Request>
@using System.Text.RegularExpressions;
@{ 
    Layout = null;
}
<table class="table table-striped table-bordered" id="main-table">
    <thead>
        <tr>
            <th>
                Request No.
            </th>
            <th>
                Requested Date
            </th>
            <th>
            </th>
            <th>
                Orders
            </th>
            <th>
                Collection Address
            </th>
            <th>
                Status
            </th>
            <th>
                Note
            </th>
            <th class="tbl-action-col">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    #@item.RequestId
                </td>
                <td>
                    @if (item.RequestedDate != null)
                    {
                        @String.Format("{0:dd/MM/yyyy hh:mm tt}", item.RequestedDate)
                    }
                </td>
                <td>
                    @if (item.RequestedDate != null)
                    {
                        @String.Format("{0:yyyyMMddHHmm}", item.RequestedDate)
                    }
                    else
                    {
                        <text>000</text>
                    }
                </td>
                <td>
                    @item.ValidOrders.Count
                </td>
                <td>@item.CollectionAddress
                </td>
                <td style="min-width: 65px;">
                    @Regex.Replace(item.Status.ToString(), "(\\B[A-Z])", " $1")
                    @if (item.Status == HDMS.Models.Statuses.RequestStatus.Draft)
                    {
                        <a class="update btn action" href="/Customer/Requests/AddOrders/@item.RequestId">
                            <img src="/img/icons/pencil.png" alt="Edit" title="Edit" /></a>   
                    }
                </td>
                <td>
                    @if (!string.IsNullOrWhiteSpace(item.Note))
                    {
                        @item.Note
                    }
                    else
                    {
                        <text>None</text>
                    }
                </td>
                <td class="action-column"@if (item.Status == HDMS.Models.Statuses.RequestStatus.Draft)
                                         {<text>style="min-wid"</text>}>
                    <a class="btn action view" href="/Customer/Requests/Details/@item.RequestId">
                        <img src="/img/icons/notepad.png" alt="View" title="View" width="15px"></a>
                    @if (item.Status == HDMS.Models.Statuses.RequestStatus.Draft)
                    {
                        <a class="btn action delete" href="#" onclick="cancelRequest(@item.RequestId);">
                            <img src="/img/icons2/cross.png" alt="Cancel" title="Cancel Request" width="15px"/>
                        </a> 
                    }
                </td>
            </tr>
        }
    </tbody>
</table>